apiVersion: v1
kind: Pod
metadata:
  name: hostpath-pod
  namespace: audit-zone
spec:
  containers:
    - name: app
      image: nginx:alpine
      volumeMounts:
        - mountPath: /data
          name: host-data
  volumes:
    - name: host-data
      hostPath:
        path: /tmp
