apiVersion: v1
kind: Namespace
metadata:
  name: client
---
apiVersion: v1
kind: Namespace
metadata:
  name: tenant
---
apiVersion: v1
kind: Namespace
metadata:
  name: smart-home
---
apiVersion: v1
kind: Namespace
metadata:
  name: accountant  
---
apiVersion: v1
kind: Namespace
metadata:
  name: ware-house
