apiVersion: v1
kind: Pod
metadata:
  name: secure-pod
  namespace: audit-zone
spec:
  containers:
    - name: app
      image: nginx:alpine
      securityContext:
        allowPrivilegeEscalation: false
        runAsNonRoot: true
        capabilities:
          drop: ["ALL"]
        seccompProfile:
          type: RuntimeDefault
